
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Motivation: 

On the 5th of August, 2019, the Indian Government imposed a communications lockdown on the disputed region of Kashmir. This lockdown has been going on for over 8 months now, with very limited information about the on-ground events being made available to the outside world. Twitter was particularly instrumental for the government in India, which, according to the Berkman Klein Center for Internet and Society at Harvard, received thousands of requests from the Indian government to withdraw tweets and accounts from Kashmiri jounralists, activists and news organizations operating across the world. 

This project is structured to investigate the requests governments across the world make for the censorship of data on Twitter, and to explore trends in this activity over the years. 

#### Project Overview: 

I will be looking at Israel, Pakistan, India, Turkey, Russia and the USA in particular since they have made the most consistent requests for content removal over time. I will analyze changes in trends and seek to investigate Twitter's compliance with these requests in relation to these countries' economic power, as well as qualitatively judge what events may have led to spikes in these countries' removal requests. I also seek to draw comparisons with Facebook, and their responses.

#### About Me: 

My name is Asmer Asrar Safi, and I'm a rising Sophomore in Leverett House planning to pursue Social Studies as a concentration. You can reach me at asmersafi@college.harvard.edu, or https://www.linkedin.com/in/asmer-asrar-safi-1b06b3185/. 


