---
title: "Cleaned_work"
author: "Asmer Asrar Safi"
date: "5/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(ggplot2)
library(fivethirtyeight)
library(tidyverse)
library(viridis)
library(transformr)
library(RColorBrewer)
library(readxl)
library(naniar)
library(dplyr)
library(readr)
library(markdown)
library(patchwork)
library(purrr)
library(stringr)
library(ggthemes)
library(tibble)
library(gganimate)
library(janitor)
library(skimr)
library(gt)
library(forcats)
library(jsonlite)
library(broom)
library(hrbrthemes)

```


```{r,include=FALSE}
mydata <- ldply(list.files(path="~/Documents/Gov 1005/Censorship-On-Social-Media/Raw-Data/Removal Requests//",pattern="csv",full.names=TRUE),function(filename) {
    dum=read_csv(filename, locale = locale(encoding = "latin1"))
    dum$filename=filename
    return(dum)
})

# Loaded Data


# Cleaning Data 


mydata <- mydata %>% 
  
  clean_names() %>% 
  
  select(-flags, -links, -report_links, -filename, -iso_code, -removal_requests_govt_agency_police_other) %>% 
  
  # Filtering and removing for extraneous variables, that are not necessary
  
  mutate(accounts_withheld = ifelse(accounts_withheld == "-", 
                                   0, 
                                   accounts_withheld), 
         
         removal_requests_court_orders = ifelse(removal_requests_court_orders == "-", 
                                   0, 
                                   removal_requests_court_orders), 
         
         removal_requests_go_va_t_agency_police_other = ifelse(removal_requests_go_va_t_agency_police_other == "-", 0, removal_requests_go_va_t_agency_police_other), 
         
         percentage_where_some_content_withheld = ifelse(percentage_where_some_content_withheld == "-", 0, percentage_where_some_content_withheld),
         
         accounts_specified = ifelse(accounts_specified == "-", 
                                   0, 
                                   accounts_specified), 
         
         accounts_withheld =  replace_na(accounts_withheld, 0),
         
         tweets_withheld = replace_na(tweets_withheld, 0),
  
         tweets_withheld = ifelse(tweets_withheld == "-", 
                                   0, 
                                   tweets_withheld),

         accounts_withheld = ifelse(accounts_withheld == "-", 
                                   0, 
                                   accounts_withheld))


mydata <- mydata %>% 
  
  mutate(tweets_withheld = ifelse(tweets_withheld == "-", 0, tweets_withheld)) %>%
  
  mutate(accounts_tos = ifelse(accounts_tos == "-", 0, accounts_tos)) %>% 
  
  mutate(removal_requests_go_vao_t_agency_police_other = ifelse(removal_requests_go_vao_t_agency_police_other == "-", 0, removal_requests_go_vao_t_agency_police_other)) %>% 
  
  mutate(accounts_no_action = ifelse(accounts_no_action == "-", 0, accounts_no_action)) %>% 
  
  
  mutate(removal_requests_go_vi_t_agency_police_other = ifelse(removal_requests_go_vi_t_agency_police_other == "-", 0, removal_requests_go_vi_t_agency_police_other)) %>% 
  
  # Replacing NAs with 0 
  
  mutate(removal_requests_go_vao_t_agency_police_other = replace_na(removal_requests_go_vao_t_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_go_va_t_agency_police_other = replace_na(removal_requests_go_va_t_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_go_vi_t_agency_police_other = replace_na(removal_requests_go_vi_t_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_government_agency_police_other = replace_na(removal_requests_government_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_court_orders = replace_na(removal_requests_court_orders, 0)) %>% 
   
  mutate(accounts_specified = replace_na(accounts_specified, 0)) %>% 
  
  mutate(accounts_withheld = replace_na(accounts_withheld, 0)) %>% 
  
  mutate(accounts_no_action = replace_na(accounts_no_action, 0)) %>% 
  
  mutate(tweets_withheld = replace_na(tweets_withheld, 0)) %>% 
  
  mutate(accounts_tos = replace_na(accounts_tos, 0)) %>% 
  
  mutate(removal_requests_government_agency_police_other = ifelse(removal_requests_government_agency_police_other == "-", 0, removal_requests_government_agency_police_other)) %>% 
  
  # Removing asterisks
  
  mutate(percentage_where_some_content_withheld = str_replace(percentage_where_some_content_withheld, "\\*", " ")) %>% 
  
  mutate(percentage_where_some_content_withheld = str_replace(percentage_where_some_content_withheld, "\\%","")) %>% 

  mutate(tweets_withheld = str_replace(tweets_withheld, "\\*", " ")) %>% 

  mutate(accounts_withheld = str_replace(accounts_withheld, "\\*", " ")) %>% 
    
  mutate(accounts_specified = str_replace(accounts_specified, "\\*", " ")) %>% 

  # Removing commas between numbers
  
  mutate(accounts_specified = gsub(",", "", accounts_specified)) %>% 
  
  mutate(accounts_withheld = gsub(",", "", accounts_withheld)) %>%
  
  mutate(tweets_withheld = gsub(",", "", tweets_withheld)) %>%
  
  mutate(removal_requests_court_orders = gsub(",", "", removal_requests_court_orders)) %>%
  
  mutate(removal_requests_go_va_t_agency_police_other = gsub(",", "", removal_requests_go_va_t_agency_police_other)) %>%
  
  mutate(percentage_where_some_content_withheld = gsub(",", "", percentage_where_some_content_withheld)) %>%
  
  mutate(accounts_tos = gsub(",", "", accounts_tos)) %>%
  
  mutate(accounts_no_action = gsub(",", "", accounts_no_action)) %>% 
  
  mutate(removal_requests_government_agency_police_other = gsub(",", "", removal_requests_government_agency_police_other)) %>%
  
  mutate(removal_requests_go_vi_t_agency_police_other = gsub(",", "", removal_requests_go_vi_t_agency_police_other)) %>% 
  
  mutate(removal_requests_go_vao_t_agency_police_other = gsub(",", "", removal_requests_go_vao_t_agency_police_other)) %>% 
  
  mutate(percentage_where_some_content_withheld = replace_na(percentage_where_some_content_withheld, 0)) %>% 
 
  # Releveling the factors in time_period variable
  
  mutate(time_period = factor(time_period, levels =
           c("January - June 2012",
             
             "July - December 2012",
             
             "January - June 2013",
             
             "July - December 2013",
             
             "January - June 2014",
             
             "July - December 2014",
             
             "January - June 2015",
             
             "July - December 2015",
             
             "January - June 2016",
             
             "July - December 2016",
             
             "January - June 2017",
             
             "July - December 2017",
             
             "January - June 2018",
             
             "July - December 2018",
             
             "January - June 2019"))) %>% 
  
  # Removing paranthetical variables
  
  mutate(tweets_withheld = gsub("\\s*\\([^\\)]+\\)\\s*$","",as.character(tweets_withheld)))




```




```{r, include=FALSE}
GDP_data <- read_csv("API_NY.GDP.MKTP.CD_DS2_en_csv_v2_988718.csv") %>% 
  
  # Reading GDP Data 
  
  clean_names() %>% 
  
  select(country_name, x2012, x2013, x2014, x2015, x2016, x2017, x2018)  %>% 
  
  # Pivoting to tidy format
  
  pivot_longer(names_to = "year", 
               
               values_to = "GDP", 
               
               cols = -country_name, 
                
               names_prefix = "x") %>% 
  
  dplyr::rename("country" = country_name) %>% 
  
  # Making country names similar to the mydata dataset
  
  mutate(country = str_replace(country, "Korea, Rep.", "South Korea")) %>% 
 
  mutate(country = str_replace(country, "Hong Kong SAR, China", "Hong Kong")) %>% 
  
  mutate(country = str_replace(country, "Venezuela, RB", "Venezuela")) %>% 
  
  mutate(country = str_replace(country, "Egypt, Arab Rep.", "Egypt")) %>% 
  
  mutate(country = str_replace(country, "Kyrgyz Republic", "Kyrgyzstan")) %>% 
  
  mutate(country = str_replace(country, "North Macedonia", "Macedonia")) %>% 
  
  mutate(country = str_replace(country, "Croatia", "Croatia")) %>% 
  
  mutate(country = str_replace(country, "Venezuela", "Venezuela"))
  
 


view(GDP_data)

``` 



```{r, include=FALSE}


# Changing Halves to years.

formodel <- mydata %>% 
  
  mutate(time_period = as.character(time_period)) %>% 
  
  mutate(time_period = str_replace(time_period, "January - June 2012", "2012")) %>%

  mutate(time_period = str_replace(time_period, "July - December 2012", "2012")) %>%

  mutate(time_period = str_replace(time_period, "January - June 2013", "2013")) %>%

  mutate(time_period = str_replace(time_period, "July - December 2013", "2013")) %>%

  mutate(time_period = str_replace(time_period, "January - June 2014", "2014")) %>%

  mutate(time_period = str_replace(time_period, "July - December 2014", "2014")) %>%

  mutate(time_period = str_replace(time_period, "January - June 2015", "2015")) %>%

  mutate(time_period = str_replace(time_period, "July - December 2015", "2015")) %>%

  mutate(time_period = str_replace(time_period, "January - June 2016", "2016")) %>%

  mutate(time_period = str_replace(time_period, "July - December 2016", "2016")) %>%

  mutate(time_period = str_replace(time_period, "January - June 2017", "2017")) %>%

  mutate(time_period = str_replace(time_period, "July - December 2017", "2017")) %>%

  mutate(time_period = str_replace(time_period, "January - June 2018", "2018")) %>%

  mutate(time_period = str_replace(time_period, "July - December 2018", "2018")) %>%

  mutate(time_period = str_replace(time_period, "January - June 2019", "2019")) %>%

  # Changing from character to numeric class
  
  mutate(accounts_withheld = as.numeric(accounts_withheld)) %>% 
  
  mutate(tweets_withheld = as.numeric(tweets_withheld)) %>% 
  
  mutate(total_withholding_accounts_and_tweets = accounts_withheld + tweets_withheld) %>% 
  
  mutate(accounts_specified = as.numeric(accounts_specified)) %>% 
  
  mutate(percentage_where_some_content_withheld = as.numeric(percentage_where_some_content_withheld)) %>% 

  dplyr::rename("year" = time_period) %>% 
  
  # Making country names alike for joining the data sets
  
  mutate(country = str_replace(country, "Czech Republuc", "Czech Republic")) %>% 
  
  mutate(country = str_replace(country, "Russia", "Russian Federation")) %>% 
  
  mutate(country = str_replace(country, "Luxemburg", "Luxembourg")) %>% 
  
  mutate(country = str_replace(country, "Tunisla", "Tunisia")) %>% 
  
  mutate(country = str_replace(country, "Crotia", "Croatia")) %>% 
  
  mutate(country = str_replace(country, "Venezuela", "Venezuela")) %>% 
  
  # Changing from character to numeric variables
  
  mutate(removal_requests_go_vao_t_agency_police_other = as.numeric(removal_requests_go_vao_t_agency_police_other), 
         
         removal_requests_go_va_t_agency_police_other = as.numeric(removal_requests_go_va_t_agency_police_other), 
         
         removal_requests_court_orders = as.numeric(removal_requests_court_orders), 
         
         removal_requests_government_agency_police_other = as.numeric(removal_requests_government_agency_police_other), 
         
         removal_requests_go_vi_t_agency_police_other = as.numeric(removal_requests_go_vi_t_agency_police_other),
         
         accounts_tos = as.numeric(accounts_tos), 
         
         accounts_no_action = as.numeric(accounts_no_action), 
         
         # Creating total_requests_made variable
         
         total_requests_made = removal_requests_court_orders + removal_requests_go_va_t_agency_police_other + removal_requests_go_vao_t_agency_police_other + removal_requests_go_vi_t_agency_police_other + removal_requests_government_agency_police_other) %>% 
  
         select(-removal_requests_court_orders, -removal_requests_go_va_t_agency_police_other,  -removal_requests_go_vao_t_agency_police_other, -removal_requests_go_vi_t_agency_police_other,  -removal_requests_government_agency_police_other) %>% 
  
   filter(!is.na(year)) %>% 
  
   # Removing Total rows

   filter(!country %in% c("Total", "TOTAL")) %>% 
  
   mutate(requests_where_content_withheld = (percentage_where_some_content_withheld*total_requests_made)/100)


``` 

```{r}

mydata1 <- mydata %>% 
  
   # FOR OVERALL EVALUATION PURPOSES
 
  # Changing from character to numeric class
  
  mutate(accounts_withheld = as.numeric(accounts_withheld)) %>% 
  
  mutate(tweets_withheld = as.numeric(tweets_withheld)) %>% 
  
  mutate(total_withholding_accounts_and_tweets = accounts_withheld + tweets_withheld) %>% 
  
  mutate(accounts_specified = as.numeric(accounts_specified)) %>% 
  
  mutate(percentage_where_some_content_withheld = as.numeric(percentage_where_some_content_withheld)) %>% 

  dplyr::rename("year" = time_period) %>% 
  
  
  # Making country names alike for joining the data sets
  
  mutate(country = str_replace(country, "Czech Republuc", "Czech Republic")) %>% 
  
  mutate(country = str_replace(country, "Russia", "Russian Federation")) %>% 
  
  mutate(country = str_replace(country, "Luxemburg", "Luxembourg")) %>% 
  
  mutate(country = str_replace(country, "Tunisla", "Tunisia")) %>% 
  
  mutate(country = str_replace(country, "Crotia", "Croatia")) %>% 
  
  mutate(country = str_replace(country, "Venezuela", "Venezuela")) %>% 
  
  # Changing from character to numeric variables
  
  mutate(removal_requests_go_vao_t_agency_police_other = as.numeric(removal_requests_go_vao_t_agency_police_other), 
         
         removal_requests_go_va_t_agency_police_other = as.numeric(removal_requests_go_va_t_agency_police_other), 
         
         removal_requests_court_orders = as.numeric(removal_requests_court_orders), 
         
         removal_requests_government_agency_police_other = as.numeric(removal_requests_government_agency_police_other), 
         
         removal_requests_go_vi_t_agency_police_other = as.numeric(removal_requests_go_vi_t_agency_police_other),
         
         accounts_tos = as.numeric(accounts_tos), 
         
         accounts_no_action = as.numeric(accounts_no_action), 
         
         # Creating total_requests_made variable
         
         total_requests_made = removal_requests_court_orders + removal_requests_go_va_t_agency_police_other + removal_requests_go_vao_t_agency_police_other + removal_requests_go_vi_t_agency_police_other + removal_requests_government_agency_police_other) %>% 
  
         select(-removal_requests_court_orders, -removal_requests_go_va_t_agency_police_other,  -removal_requests_go_vao_t_agency_police_other, -removal_requests_go_vi_t_agency_police_other,  -removal_requests_government_agency_police_other) %>% 
  
   filter(!is.na(year)) %>% 
  
   # Removing Total rows

   filter(!country %in% c("Total", "TOTAL")) %>% 
  
   mutate(requests_where_content_withheld = (percentage_where_some_content_withheld*total_requests_made)/100) %>% 
  
    mutate(year = factor(year, levels =
           c("January - June 2012",
             
             "July - December 2012",
             
             "January - June 2013",
             
             "July - December 2013",
             
             "January - June 2014",
             
             "July - December 2014",
             
             "January - June 2015",
             
             "July - December 2015",
             
             "January - June 2016",
             
             "July - December 2016",
             
             "January - June 2017",
             
             "July - December 2017",
             
             "January - June 2018",
             
             "July - December 2018",
             
             "January - June 2019"))) 
  
 

  write.csv(x = mydata1, "mydata1.csv")

  


  mydata1

```

```{r, join for model and GDP_data, include=FALSE}


# joining the data to create model between GDP and content withheld

# GDP only available till 2018

join_for_model <- formodel %>% 
     
   left_join(GDP_data, 
             
             by = c("year", "country")) %>% 
  
   dplyr::rename("gdp" = GDP) %>% 
  
   # Removing years that are NA (corresponding to Total rows)
  
   filter(!is.na(year)) %>% 
  
   # Removing Total rows
  
   filter(!country %in% c("Total", "TOTAL")) %>% 
  
   # mutate(gdp =  replace_na(gdp, 0)) %>% 
   
   filter(!year == "2019") 
  
  

join_for_model


write.csv(x = join_for_model, "twitter_gdp.csv")


```




#### Percentage Withheld against GDP

```{r, warning=FALSE, echo=FALSE}
model_1_perc_gdp <- join_for_model %>%

   ggplot(aes(gdp, percentage_where_some_content_withheld)) +

   geom_point() + 
  
   geom_jitter(position = "dodge") +

   geom_smooth(aes(gdp, percentage_where_some_content_withheld), method = "lm", se = TRUE) +

   scale_x_log10() +

   theme_classic() +
  
   labs(y = "Percentage of Requests by a 
      Country Where Some Content Withheld",
        
        x = "Country GDP (2019 Dollars)")

model_1_perc_gdp


model_1 <- lm(percentage_where_some_content_withheld ~ gdp, data = join_for_model) %>% 
  
  tidy(conf.int = TRUE) %>% 
  
  select(term, estimate, conf.low, conf.high) %>% 
  
  mutate(term = str_replace(term, "gdp", "GDP")) %>% 
  
  gt() %>% 
  
  cols_label(term = "Term", 
             
             estimate = "Estimate",
             
             conf.low = "Lower Bound",
             
             conf.high = "Upper Bound") %>% 
  
  tab_header(title = "Effect of Country GDP on Percentage of Content Twitter Withholds", 
             subtitle = "Higher GDP suggests more content wittheld")



model_1

```

#### Percentage Withheld against GDP = By Year

```{r, warning=FALSE, echo=FALSE}

model_2_year_perc_gdp <- join_for_model %>%
  
   filter(country %in% c("Argentina", "Australia", "Belgium", "Brazil", "Canada", "France", "Germany", "India", "Ireland", "Israel", "Japan", "Netherlands", "New Zealand", "Russia", "South Korea", "Spain", "Turkey", "United Kingdom")) %>% 
   
   # filter(year %in% 2012) %>% 
 
   ggplot(aes(gdp, percentage_where_some_content_withheld, size = total_requests_made)) +

   geom_point(aes(size = total_requests_made), alpha = 0.5) + 
  
   geom_jitter(position = "dodge", alpha = 0.5) +

   geom_smooth(aes(gdp, percentage_where_some_content_withheld), method = "lm", se = TRUE) +

   scale_x_log10() +

   theme_classic() +
  
   labs(y = "Percentage of Requests by a 
      Country Where Some Content Withheld",
        
        x = "Country GDP (2010 Dollars)") 
  
  # facet_wrap(~year)

model_2_year_perc_gdp

``` 


#### Choose country and see relationship 

##### Amount of plots vary by when and in which year the country made requests

```{r, warning=FALSE, echo=FALSE}

model_3_country_perc_gdp <- function(x){
  
  join_for_model %>%
  
   filter(country == x) %>% 

   ggplot(aes(gdp, percentage_where_some_content_withheld)) +
   geom_point() + 
   geom_jitter(position = "dodge") +
   geom_smooth(aes(gdp, percentage_where_some_content_withheld), method = "lm", se = TRUE) +
   theme_classic() +
   labs(title = print(x),
       y = "Percentage of Requests by the 
      Country Where Some Content was Withheld",
        x = "Country GDP (2019 Dollars)") 
}


model_3_country_perc_gdp("Russian Federation")


# kyun <- join_for_model %>%
  
ggplot(aes(total_requests_made, percentage_where_some_content_withheld)) +
   geom_point() + 
   geom_jitter(position = "dodge") +
   
   geom_smooth(aes(total_requests_made, percentage_where_some_content_withheld), method = "lm", se = TRUE) +
   scale_x_log10() +
   theme_classic()


```

```{r, load freedom index data}

freedom_index_data <- read_excel("2020_All_Data_FIW_2013-2020.xlsx", skip = 1) %>% 
  
  clean_names() %>% 

  select(country_territory, region, edition, total) %>% 
  
  dplyr::rename("year" = edition) %>% 
  
  dplyr::rename("country" = country_territory) %>% 
  
  dplyr::rename("freedom_score" = total) %>% 
  
  mutate(country = str_replace(country, "Russia", "Russian Federation")) 
 

freedom_index_data
```

```{r}

# Rejoining the GDP and for_model data for the purposes of this second regression
# Since there is data available for 2019 here


join_for_model_2 <- formodel %>% 
     
   left_join(GDP_data, 
             
             by = c("year", "country")) %>% 
  
   dplyr::rename("gdp" = GDP) %>% 
  
   # Removing years that are NA (corresponding to Total rows)
  
   filter(!is.na(year)) %>% 
  
   # Removing Total rows

   filter(!country %in% c("Total", "TOTAL"))



 # freedom data for 2012 not available

 join_for_model_2 <- join_for_model_2 %>%

   mutate(year = as.numeric(year))


 join_freedom_twitter <- join_for_model_2 %>%

  left_join(freedom_index_data,

             by = c("year", "country")) %>%
   
  filter(!year %in% "2012") %>% 
   
  filter(!is.na(freedom_score))





```


```{r, warning = FALSE}


join_freedom_twitter %>% 
  
 filter(country %in% c("Argentina", "Australia", "Belgium", "Brazil", "Canada", "France", "Germany", "India", "Ireland", "Israel", "Japan", "Netherlands", "New Zealand", "Russia", "South Korea", "Spain", "Turkey", "United Kingdom")) %>%
  
ggplot(aes(freedom_score, percentage_where_some_content_withheld, size = total_requests_made)) + 
  
  geom_point() +
  
  # scale_y_continuous(limits = c(0, 10000)) +
  
  # scale_y_log10() +
  
  geom_jitter(position = "dodge") +
  
  geom_smooth(aes(freedom_score, percentage_where_some_content_withheld), method = "lm") +
  
  theme_classic() 



```

```{r}
unique_countries <- 
  join_for_model %>% 
  select(country) %>% 
  unique() %>%  
  arrange(country) %>% 
  mutate(clean = country) %>% 
  # mutate(clean = tolower(country)) %>% 
  # mutate(clean = str_replace(clean, " ", "_")) %>% 
  select(clean, country) %>% 
  # mutate(clean = str_replace(clean, "bosnia_and herzegovina", "bosnia_and_herzegovina")) %>% 
  mutate(clean = shQuote(clean)) %>% 
  mutate(country = shQuote(country)) %>%
  mutate(country = paste(country, sep = ",")) %>% 
  mutate(both = paste(clean, "=", country)) %>% 
  mutate(both = paste(both,","))
  
unique_countries

write.csv(x = unique_countries, "unique_countries.csv")
  
```

```{r, Visualizations}

# For Visualization page - use mydata1 since the time_periods are ungrouped
 
# Accounts in Twitter Service Violations over Time

tos <-mydata1 %>%
  ggplot(aes(year, accounts_tos)) +
  geom_col() +
  theme_minimal() +

  labs(y = "Accounts in Violation of Twitter
    Terms of Service",

       x = "Time Period",

       caption =
      "Twitter completely removed the content from Twitter after determining it violated Twitter’s TOS.
    It states that it review all reported content for violations of Twitter’s TOS before assessing it further. (Source: Twitter)") +

   theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6))



tos


# Total requests made over time

total_requests <- mydata1 %>%

  ggplot(aes(year, total_requests_made)) +
  geom_col() +
  theme_minimal() +

  labs(y = "Total Requests Made",

       x = "Time Period",

       caption =
      "This  includes the total number of legal requests from government agencies,
police departments, or other authorized requesters within a country.") +

   theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6))

total_requests

# Total Requests where some content withheld over time


withheld_requests <- mydata1 %>%
   ggplot(aes(year, requests_where_content_withheld)) +
  geom_col() +
  theme_minimal() +

  labs(y = "Government requests where some
      content withheld",

       x = "Time Period",

       caption =
      "This  includes the total number of legal requests from government agencies,
police departments, or other authorized requesters within a country, where some content was withheld.") +

   theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6))

withheld_requests

# accounts_specified over time

specified_ac <- mydata1 %>%
  ggplot(aes(year, accounts_specified)) +
  geom_col() +
  theme_minimal() +
  labs(y = "Accounts specified for withholding
       by Governments",

       x = "Time Period",

       caption =
      "This includes the unique number of accounts identified in
the requests Twitter received. (Source: Twitter)") +

   theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6))

specified_ac

# Accounts withheld by twitter from the accounts specified

withheld_ac <- mydata1 %>%
  ggplot(aes(year, accounts_withheld)) +
  geom_col() +
  theme_minimal() +
  labs(y = "Accounts withheld by Twitter (from
       accounts specified)",

       x = "Time Period",

       caption =
      "This includes the number of accounts withheld from the
the accounts specified by Governments. (Source: Twitter)") +

   theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6))

withheld_ac

# tweets withheld

withheld_tw <- mydata1 %>%
  filter(country == "United Kingdom")
  ggplot(aes(year, tweets_withheld)) +
  geom_col() +
  theme_minimal() +
  labs(y = "Tweets withheld by Twitter",

       x = "Time Period",

       caption =
      "This includes the number of tweets withheld by Twitter on
      government request. (Source: Twitter)") +

   theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6))  +
    

withheld_tw


# total_tw_ac <-

  mydata1 %>%
  group_by(country) %>%
 summarise(c = sum(total_withholding_accounts_and_tweets))
  # mutate(year_total_cwc = count(total_withholding_accounts_and_tweets)) %>%
  # select(year, total_withholding_accounts_and_tweets, year_total_cwc)

  ggplot(aes(year, year_total_cwc)) +
  geom_col() +
  # geom_label(aes(label = scales::comma(total_withholding_accounts_and_tweets)),
  #            size = 2.5,
  #            nudge_y = 0.5) +
  theme_minimal() +
  # labs(y = "Sum of Tweets and Accounts Withheld",
  #
#   #      x = "Time Period",
#   #
#   #      caption =
# "This includes the number of tweets and accounts withheld by Twitter on
# government request.") +
#   #
#   #  theme(axis.text.x = element_text(angle = 45,
#   #                                  hjust = 1,
#   #                                  size = 6))

# total_tw_ac

# 



```


```{r}

a <- join_freedom_twitter %>% 
  group_by(year) %>% 
  mutate(mean_score = mean(freedom_score)) %>%
  mutate(totalreqyr = sum(total_requests_made)) %>% 
  ungroup() %>%
  filter(country == "Argentina") %>%

  ggplot(aes(year, freedom_score)) +
  geom_line(aes(year, freedom_score),
            color = "grey") +
  geom_point(aes(size = total_requests_made),
             shape=21,
             color="black",
             alpha = 0.5,
             fill="#69b3a2") +
  geom_line(aes(year, mean_score),
            color = "grey",
            linetype = "dashed") +
  geom_point(aes(year, mean_score, size = totalreqyr),
             color = "black",
             shape = 21,
             alpha = 0.5,
             fill = "darkred") +
  theme_minimal() +
  labs(y = "Freedom Score",
       x = "Year",
       title = "India",
       subtitle = "Freedom score and total requests made for content withholding (2013-2019)",
       caption = "
Dashed line representes the year's mean freedom score for all countries. The solid line represents
the specific country's freedom scores. Data from Freedom House.",
       size = "Total Requests Made") +
  theme(plot.title = element_text(face = "bold",
                                  size = 15,
                                  hjust = 0.5),
        plot.subtitle = element_text(face = "italic",
                                  size = 10,
  hjust = 0.5),
        plot.caption = element_text(face = "italic",
                                    hjust = 0.5)) 




 # write.csv(x = join_freedom_twitter, "freedom_twitter_gdp.csv")


```








