
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Data Gathering and Processing

The primary data for this final project is from the [Twitter Transparency Reports](https://transparency.twitter.com/). The secondary data for this Project was obtained from the [Facebook Transparency Reports](https://transparency.facebook.com/government-data-requests) and the Berkman Klein Center for Internet and Society's Lumen Project at Harvard University. 

The Twitter Transparency Report data is further subdivided into [Removal Requests](https://transparency.twitter.com/en/removal-requests.html) and [Information Requests](https://transparency.twitter.com/en/information-requests.html) made by governments from January 2012 to June 2019. The latest reports (July 2019 - December 2019) are yet to be released. 

The data is grouped by time periods of January to June, and July to December for each year, with requests made by courts, government institutions, law-enforcement agencies being documented in each data set. Each data set also documents the requests complied with (in terms of both accounts and tweets), with URLs to the withheld data. 

All the data analysis is conducted using information from the aforementioned data sources. 

