---
title: "Censorship-on-Social-Media-1"
author: "Asmer Asrar Safi"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(fivethirtyeight)
library(tidyverse)
library(transformr)
library(naniar)
library(dplyr)
library(readr)
library(markdown)
library(patchwork)
library(purrr)
library(stringr)
library(ggthemes)
library(tibble)
library(gganimate)
library(janitor)
library(skimr)
library(gt)
library(forcats)
library(broom)
library(plyr)
```


```{r, load the data, include=FALSE, message=FALSE}


# LOADING the relevant removal requests data 
mydata <- ldply(list.files(path="~/Documents/Gov 1005/Censorship-On-Social-Media/Raw-Data/Removal Requests//",pattern="csv",full.names=TRUE),function(filename) {
    dum=read_csv(filename, locale = locale(encoding = "latin1"))
    dum$filename=filename
    return(dum)
})



mydata <- mydata %>% 
  clean_names() %>% 
  select(-flags, -links, -report_links, -filename, -iso_code, -removal_requests_govt_agency_police_other) %>% 
  mutate(accounts_withheld = ifelse(accounts_withheld == "-", 
                                   0, 
                                   accounts_withheld), 
         
         removal_requests_court_orders = ifelse(removal_requests_court_orders == "-", 
                                   0, 
                                   removal_requests_court_orders), 
         
         removal_requests_go_va_t_agency_police_other = ifelse(removal_requests_go_va_t_agency_police_other == "-", 0, removal_requests_go_va_t_agency_police_other), 
         
         percentage_where_some_content_withheld = ifelse(percentage_where_some_content_withheld == "-", 0, percentage_where_some_content_withheld),
         
         accounts_specified = ifelse(accounts_specified == "-", 
                                   0, 
                                   accounts_specified), 
         
         accounts_withheld =  replace_na(accounts_withheld, 0),
         
         tweets_withheld = replace_na(tweets_withheld, 0),
  
         tweets_withheld = ifelse(tweets_withheld == "-", 
                                   0, 
                                   tweets_withheld),

         accounts_withheld = ifelse(accounts_withheld == "-", 
                                   0, 
                                   accounts_withheld))


mydata <- mydata %>% 
  
  mutate(tweets_withheld = ifelse(tweets_withheld == "-", 0, tweets_withheld)) %>%
  
  mutate(accounts_tos = ifelse(accounts_tos == "-", 0, accounts_tos)) %>% 
  
  mutate(removal_requests_go_vao_t_agency_police_other = ifelse(removal_requests_go_vao_t_agency_police_other == "-", 0, removal_requests_go_vao_t_agency_police_other)) %>% 
  
  mutate(accounts_no_action = ifelse(accounts_no_action == "-", 0, accounts_no_action)) %>% 
  
  
  mutate(removal_requests_go_vi_t_agency_police_other = ifelse(removal_requests_go_vi_t_agency_police_other == "-", 0, removal_requests_go_vi_t_agency_police_other)) %>% 
  
  
  mutate(removal_requests_go_vao_t_agency_police_other = replace_na(removal_requests_go_vao_t_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_go_va_t_agency_police_other = replace_na(removal_requests_go_va_t_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_go_vi_t_agency_police_other = replace_na(removal_requests_go_vi_t_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_government_agency_police_other = replace_na(removal_requests_government_agency_police_other, 0)) %>% 
  
  mutate(removal_requests_court_orders = replace_na(removal_requests_court_orders, 0)) %>% 
   
  mutate(accounts_specified = replace_na(accounts_specified, 0)) %>% 
  
  mutate(accounts_withheld = replace_na(accounts_withheld, 0)) %>% 
  
  mutate(accounts_no_action = replace_na(accounts_no_action, 0)) %>% 
  
  mutate(tweets_withheld = replace_na(tweets_withheld, 0)) %>% 
  
  mutate(accounts_tos = replace_na(accounts_tos, 0)) %>% 
  
  mutate(removal_requests_government_agency_police_other = ifelse(removal_requests_government_agency_police_other == "-", 0, removal_requests_government_agency_police_other)) %>% 
  
  mutate(percentage_where_some_content_withheld = str_replace(percentage_where_some_content_withheld, "\\*", " ")) %>% 
  
  mutate(percentage_where_some_content_withheld = str_replace(percentage_where_some_content_withheld, "\\%","")) %>% 

  mutate(tweets_withheld = str_replace(tweets_withheld, "\\*", " ")) %>% 

  mutate(accounts_withheld = str_replace(accounts_withheld, "\\*", " ")) %>% 
    
  mutate(accounts_specified = str_replace(accounts_specified, "\\*", " ")) %>% 

  mutate(accounts_specified = gsub(",", "", accounts_specified)) %>% 
  
  mutate(accounts_withheld = gsub(",", "", accounts_withheld)) %>%
  
  mutate(tweets_withheld = gsub(",", "", tweets_withheld)) %>%
  
  mutate(removal_requests_court_orders = gsub(",", "", removal_requests_court_orders)) %>%
  
  mutate(removal_requests_go_va_t_agency_police_other = gsub(",", "", removal_requests_go_va_t_agency_police_other)) %>%
  
  mutate(percentage_where_some_content_withheld = gsub(",", "", percentage_where_some_content_withheld)) %>%
  
  mutate(accounts_tos = gsub(",", "", accounts_tos)) %>%
  
  mutate(accounts_no_action = gsub(",", "", accounts_no_action)) %>% 
  
  mutate(removal_requests_government_agency_police_other = gsub(",", "", removal_requests_government_agency_police_other)) %>%
  
  mutate(removal_requests_go_vi_t_agency_police_other = gsub(",", "", removal_requests_go_vi_t_agency_police_other)) %>% 
  
  mutate(removal_requests_go_vao_t_agency_police_other = gsub(",", "", removal_requests_go_vao_t_agency_police_other)) %>% 
  
  mutate(percentage_where_some_content_withheld = replace_na(percentage_where_some_content_withheld, 0)) %>% 
 
  mutate(time_period = factor(time_period, levels =
           c("January - June 2012",
             
             "July - December 2012",
             
             "January - June 2013",
             
             "July - December 2013",
             
             "January - June 2014",
             
             "July - December 2014",
             
             "January - June 2015",
             
             "July - December 2015",
             
             "January - June 2016",
             
             "July - December 2016",
             
             "January - June 2017",
             
             "July - December 2017",
             
             "January - June 2018",
             
             "July - December 2018",
             
             "January - June 2019")))
  
  




```


```{r}

p <- mydata %>% 
mutate(percentage_where_some_content_withheld = as.numeric(percentage_where_some_content_withheld)) %>% 
group_by(country) %>% 
ggplot(aes(time_period, percentage_where_some_content_withheld, color = country)) +
         geom_point() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6),
        axis.text.y = element_text(size = 6))

p
```




```{r, wrangling, echo=FALSE}
# filtering for the relevant countries

wrangledata <- mydata %>% 
  filter(country %in% c("Pakistan", "India", "Turkey", "Israel", "United States", "Russia"))


wrangledata$accounts_specified <- as.numeric(wrangledata$accounts_specified)

wrangledata$time_period <- as.factor(wrangledata$time_period)

wrangledata$time_period <- factor(wrangledata$time_period, levels =
           c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))

wrangledata <- 
  wrangledata %>% 
  mutate(accounts_specified = replace_na(accounts_specified, 0)) 
wrangledata

```




```{r}



Plot1 <- wrangledata %>% 
select(country,
       accounts_specified,
       time_period) %>% 
ggplot(aes(x = time_period,
           y = accounts_specified, 
           color = country)) + 
  geom_point() +
  geom_line() +
  scale_color_stata() +
  theme_few() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6),
        axis.text.y = element_text(size = 6)) +
  labs(x = "Time Period", 
       y = "Accounts Specified",
       color = "Country", 
       title = "Accounts Specified for Content Withdrawal
from January 2012 to June 2019",
subtitle = "Data from Twitter Transparency Reports") 

Plot1
```


```{r}

Plot2 <- wrangledata %>% 
select(country,
       accounts_specified,
       time_period) %>% 
ggplot(aes(x = time_period,
           y = accounts_specified, 
           color = country)) + 
  geom_point() +
  geom_line(group = 1) +
  scale_color_stata() +
  theme_few() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6),
        axis.text.y = element_text(size = 6)) +
  labs(x = "Time Period", 
       y = "Accounts Specified",
       color = "Country", 
       title = "Accounts Specified for Content Withdrawal
from January 2012 to June 2019",
subtitle = "Data from Twitter Transparency Reports") +
 facet_wrap(~country) 

Plot2

```


```{r}

wrangledata$percentage_where_some_content_withheld = as.numeric(gsub("[\\%,]", "", wrangledata$percentage_where_some_content_withheld))

wrangledata <- 
  wrangledata %>% 
  mutate(percentage_where_some_content_withheld = replace_na(percentage_where_some_content_withheld, 0)) 

Plot3 <- wrangledata %>% 
  ggplot(aes(time_period, 
             percentage_where_some_content_withheld,
             color = country)) +
  geom_point() + 
  theme_few() + 
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 6),
        axis.text.y = element_text(size = 6)) +
  labs(x = "Time Period", 
       y = "Percentage of Requests Complied with",
       color = "Country", 
       title = "Percentage of Requests Complied with by Twitter
January 2012 - June 2019",
subtitle = "Data from Twitter Transparency Reports") +
  scale_color_stata()

Plot3
```


```{r, total tweet requests all data}

# Retrieving total - create function for columns. 

# Tracks total contents specified over time periods for withdrawal

mydata$accounts_specified <- as.numeric(mydata$accounts_specified)

mydata$time_period <- as.factor(mydata$time_period)

mydata$time_period <- factor(mydata$time_period, levels =
           c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))

mydata <- 
  mydata %>% 
  mutate(accounts_specified = replace_na(accounts_specified, 0)) 


get_total <- function(x){
 mydata %>% 
  filter(time_period == x) %>% 
  summarize(total = sum(accounts_specified)) %>% 
  pull(total)
}

get_total("January - June 2014")


total_accounts_specified <- 
  tibble(time_period = c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))

total_accounts_specified$time_period <- factor(total_accounts_specified$time_period, levels =
           c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))


total_accounts_specified$time_period <- as.factor(total_accounts_specified$time_period)

total_accounts_specified <- total_accounts_specified %>% 
  mutate(total_accounts = map_dbl(time_period, get_total))

Plot4 <- total_accounts_specified %>% 
  ggplot(aes(time_period, total_accounts)) + 
  scale_color_solarized() +
  geom_line(aes(group = 1, color = "darkblue")) +
  geom_point(color = "darkblue") +
  theme_few() +
   labs(x = "Time Period", 
       y = "Total Number of Accounts Specified in Given Time Period",
       color = "Country", 
       title = "Total Number of Accounts Specified
January 2012 - June 2019",
caption = "Data from Twitter Transparency Reports") + 
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 7),
        axis.text.y = element_text(size = 7),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 8)) + 
  theme(legend.position = "none") 
Plot4

ggsave("Plot4.jpg", last_plot())

```


```{r, total content withheld after request}

# Creating content withheld for each country column by adding tweets_withheld and accounts_withheld 



mydataforcontentwithheldtotal <- 
  mydata %>% 
  mutate(accounts_withheld = replace_na(accounts_withheld, 0)) %>% 
  mutate(tweets_withheld = replace_na(tweets_withheld, 0)) %>% 
  select(time_period, country, tweets_withheld, accounts_withheld) %>%  
  mutate(tweets_withheld = ifelse( tweets_withheld == "-", 
                                   0, 
                                   tweets_withheld)) %>% 
  mutate(accounts_withheld = ifelse(accounts_withheld == "-", 
                                   0, 
                                   accounts_withheld)) %>% 
  mutate(accounts_withheld = str_replace(accounts_withheld, '\\*', '')) %>% 
  mutate(tweets_withheld = str_replace(accounts_withheld, '\\*', '')) %>% 
  mutate(accounts_withheld = as.numeric(accounts_withheld)) %>% 
  mutate(tweets_withheld = as.numeric(tweets_withheld)) %>% 
  mutate(content_withheld = accounts_withheld + tweets_withheld) 
                                    

get_total_content_withheld <- function(x){
 mydataforcontentwithheldtotal %>% 
  filter(time_period == x) %>% 
  filter(!country == "TOTAL", !country == "Total") %>% 
  summarize(total = sum(content_withheld)) %>% 
  pull(total) 
}

get_total_content_withheld("January - June 2019")


total_content_withheld <- tibble(time_period = c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))

total_content_withheld$time_period <- factor(total_content_withheld$time_period, levels =
           c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))

total_content_withheld <- total_content_withheld %>% 
              mutate(total_content_withheld_TP = map_dbl(time_period, get_total_content_withheld))



Plot5 <- total_content_withheld %>% 
  ggplot(aes(time_period, total_content_withheld_TP)) +
  geom_point(color = "darkgreen") +
  geom_line(color = "darkgreen", group = 1) +
  scale_color_stata() +
  theme_few() +
  labs(x = "Time Period", 
       y = "Total Content Withheld in Given Time Period", 
       title = "Total Content Withheld,
January 2012 - June 2019",
caption = "Data from Twitter Transparency Reports") +
     theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 7),
        axis.text.y = element_text(size = 7),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 8)) 

Plot5

ggsave("Plot.5.jpg", last_plot())
```



















