

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(fivethirtyeight)
library(tidyverse)
library(transformr)
library(naniar)
library(dplyr)
library(readr)
library(patchwork)
library(purrr)
library(stringr)
library(ggthemes)
library(tibble)
library(gganimate)
library(janitor)
library(skimr)
library(gt)
library(forcats)
library(broom)
library(plyr)
```


```{r, message=FALSE, include=FALSE, warning=FALSE}

# LOADING the relevant removal requests data 
mydata <- ldply(list.files(path="~/Documents/Gov 1005/Censorship-On-Social-Media/Raw-Data/Removal Requests//",pattern="csv",full.names=TRUE),function(filename) {
    dum=read_csv(filename, locale = locale(encoding = "latin1"))
    dum$filename=filename
    return(dum)
})
mydata <- mydata %>% 
  clean_names() 
```

```{r, echo=FALSE,warning=FALSE}
# Retrieving total - create function for columns. 

# Tracks total contents specified over time periods for withdrawal

mydata$accounts_specified <- as.numeric(mydata$accounts_specified)

mydata$time_period <- as.factor(mydata$time_period)

mydata$time_period <- factor(mydata$time_period, levels =
           c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))

mydata <- 
  mydata %>% 
  mutate(accounts_specified = replace_na(accounts_specified, 0)) 


get_total <- function(x){
 mydata %>% 
  filter(time_period == x) %>% 
  summarize(total = sum(accounts_specified)) %>% 
  pull(total)
}


total_accounts_specified <- 
  tibble(time_period = c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))

total_accounts_specified$time_period <- factor(total_accounts_specified$time_period, levels =
           c("January - June 2012",
             "July - December 2012",
             "January - June 2013",
             "July - December 2013",
             "January - June 2014",
             "July - December 2014",
             "January - June 2015",
             "July - December 2015",
             "January - June 2016",
             "July - December 2016",
             "January - June 2017",
             "July - December 2017",
             "January - June 2018",
             "July - December 2018",
             "January - June 2019"))


total_accounts_specified$time_period <- as.factor(total_accounts_specified$time_period)

total_accounts_specified <- total_accounts_specified %>% 
  mutate(total_accounts = map_dbl(time_period, get_total))

Plot4 <- total_accounts_specified %>% 
  ggplot(aes(time_period, total_accounts)) + 
  scale_color_solarized() +
  geom_line(aes(group = 1, color = "darkblue")) +
  geom_point(color = "darkblue") +
  theme_few() +
   labs(x = "Time Period", 
       y = "Total Number of Accounts Specified in Given Time Period",
       color = "Country", 
       title = "Total Number of Accounts Specified
January 2012 - June 2019",
caption = "Data from Twitter Transparency Reports") + 
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   size = 7),
        axis.text.y = element_text(size = 7),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 8)) + 
  theme(legend.position = "none") 
Plot4
```

